### ISSUE TITLE
Some Permission errors!!

### ISSUE THREAD

**Issue by jteslaxxx** [bssh2/SSH-Brute-Force-Scanner#1]
When I try to scan some ip range, class I get some permission errors and output like this:
############################
# GOOD for ROOTs and USERs #
############################
scan_root: line 13: ./ss: Permission denied
cat: bios.txt: No such file or directory
scan_root: line 16: ./ssh2: Permission denied
I tried to chmod +x, get same errors! Is there any specifications where scanner should be? Could you please share some more instructions of use of script? 
I,m running on Kali Rolling!

**Comment by jteslaxxx** [comment]
Sorry i missed one file to chmod seems to work fine now!!

**Comment by jteslaxxx** [comment]
One more question, its only for scanning right? Its actually does not brute the system???

**Comment by sshbruteforce** [comment]
Yes , is only for proof vulnerability remote or local . This software is intended for testing only. Please use it at your own risk!

**Comment by jteslaxxx** [comment]
Yes understood, strange is that i get no vun.. output!!
